//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chip
    {
        public string chip_imei { get; set; }
        public string chip_operadora { get; set; }
        public Nullable<System.DateTime> chip_data_envio { get; set; }
        public Nullable<long> cli_id { get; set; }
        public Nullable<double> chip_status { get; set; }
        public int chip_id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
