//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Procedimentos
    {
        public long cli_id { get; set; }
        public int proc_id { get; set; }
        public int cli_proc_id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Procedimentos Procedimentos { get; set; }
    }
}
