//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente_Servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente_Servico()
        {
            this.Servico_Tipo_Comunic = new HashSet<Servico_Tipo_Comunic>();
        }
    
        public int cli_serv_id { get; set; }
        public long cli_id { get; set; }
        public int serv_id { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Servicos_Presdados Servicos_Presdados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servico_Tipo_Comunic> Servico_Tipo_Comunic { get; set; }
    }
}
