//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int emp_id { get; set; }
        public string emp_razao_social { get; set; }
        public string emp_endereco { get; set; }
        public string emp_bairro { get; set; }
        public string emp_cidade { get; set; }
        public string emp_telefone { get; set; }
        public string emp_email { get; set; }
        public string emp_cnpj { get; set; }
        public string emp_cep { get; set; }
        public string emp_uf { get; set; }
        public Nullable<bool> emp_status { get; set; }
        public string emp_nome_fantasia { get; set; }
        public Nullable<System.DateTime> emp_data_abertura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
