//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int log_id { get; set; }
        public string log_user { get; set; }
        public string log_pass { get; set; }
        public string log_nome { get; set; }
        public Nullable<int> log_nivel { get; set; }
        public string log_senha_falada { get; set; }
        public Nullable<bool> log_acesso_sistema { get; set; }
        public byte[] log_senha { get; set; }
        public Nullable<long> cli_id { get; set; }
    }
}
