//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class monitoramentoEntities : DbContext
    {
        public monitoramentoEntities()
            : base("name=monitoramentoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chip> Chip { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Cliente_Procedimentos> Cliente_Procedimentos { get; set; }
        public virtual DbSet<Cliente_Servico> Cliente_Servico { get; set; }
        public virtual DbSet<Cliente_Usuario_Alarme> Cliente_Usuario_Alarme { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Leitor> Leitor { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<OS> OS { get; set; }
        public virtual DbSet<OS_Tecnico> OS_Tecnico { get; set; }
        public virtual DbSet<Procedimentos> Procedimentos { get; set; }
        public virtual DbSet<Receptores> Receptores { get; set; }
        public virtual DbSet<Servico_Tipo_Comunic> Servico_Tipo_Comunic { get; set; }
        public virtual DbSet<Servicos_Presdados> Servicos_Presdados { get; set; }
        public virtual DbSet<Tecnico> Tecnico { get; set; }
        public virtual DbSet<Tipo_Comunicacao> Tipo_Comunicacao { get; set; }
        public virtual DbSet<Usuario_Alarme> Usuario_Alarme { get; set; }
    }
}
