//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Collections.Generic;
    
    public partial class OS_Tecnico
    {
        public long os_id { get; set; }
        public int tec_id { get; set; }
        public long os_tec_id { get; set; }
    
        public virtual OS OS { get; set; }
        public virtual Tecnico Tecnico { get; set; }
    }
}
