//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receptores()
        {
            this.Leitor = new HashSet<Leitor>();
        }
    
        public int recep_id { get; set; }
        public string recep_modelo { get; set; }
        public string eve_conta_grupo_receptor { get; set; }
        public string recep_tipo_comunicacao { get; set; }
        public string recep_cidade { get; set; }
        public string recep_obs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leitor> Leitor { get; set; }
    }
}
