//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monial
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico_Tipo_Comunic
    {
        public int serv_tipo_com_id { get; set; }
        public int comunic_id { get; set; }
        public int cli_serv_id { get; set; }
    
        public virtual Cliente_Servico Cliente_Servico { get; set; }
        public virtual Tipo_Comunicacao Tipo_Comunicacao { get; set; }
    }
}
